---
## Chapter-13/encrypted-string-playbook.yaml
- name: Using encrypted variables
  hosts: node1
  vars:
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62386361656532643262336363633636303262663738663134613439383938326335336237303463
          6138323038373665643164303531343431366232663666350a643362323264373532393036323361
          31393332613566303064343463613630353235316530343632363564323738633532666235353930
          3466663030386634300a633334386439656530663431343237626534623137326465363665643034
          64663932363236363939373561643739663339373139356539373032643565326233

  tasks:

    - name: Print a message
      ansible.builtin.debug:
        msg: 'Password is: {{ password }}'


  